### ISSUE TITLE
Sorting of numeric columns is wrong

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#153]
![image](https://user-images.githubusercontent.com/109126/97423862-2f612980-1910-11eb-90d3-dd7c168e3dee.png)

There's an interesting question as to how negative and positive changes should be related - ~~perhaps ordering by absolute value would be best?~~ Nah, that's crazy on second thought.

**Comment by I-Al-Istannen** [comment]
I should probably expand and work on merging the UI test cases to catch such regressions...

The problem is that it sorts based on the *formatted* value.

I also wondered about the sorting order a while ago, but I have no idea what's useful. If the metrics are wildly different, a change of 0.002 could be much more important than a change by a few thousand (e.g. binary size in bytes). I feel like sorting by value should somehow capture this? One could sort by the relative difference (what the home page displays), but not all values have a standard deviation.  
Sorting the change percent column might also somewhat alleviate this, but I am not sure what's the best option here.
