### ISSUE TITLE
Runners report maximum Java heap size, not available system memory

### ISSUE THREAD

**Issue by fread** [IPDSnelting/velcom#16]
On the Queue page, the runners report their "max RAM", but this does not appear to be the amount of RAM actually present in the system.

It looks like the runners use `Runtime.getRuntime().maxMemory()` to get this number (see https://github.com/IPDSnelting/velcom/blob/abe30dd4c19e7e8aa09128407bdda5ac6e2c64c7/backend/runner/src/main/java/de/aaaaaaah/velcom/runner/state/RunnerStateMachine.java#L65). But according to the Java documentation (https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#maxMemory--), this method only returns "the maximum amount of memory that the Java virtual machine will attempt to use", which sounds like the max-heap setting to me.

The runners should instead report the amount of RAM present (or better yet free) in the system.

**Comment by I-Al-Istannen** [comment]
That's correct. As the runner only needs to run on Linux and a dependency on JNA/OSHI seemed a bit heavy, the runner [will likely use the procfs](https://github.com/IPDSnelting/velcom/commit/d0f176793e9cf678e61dbc7bbbfa59f22660ae40) (`/proc/cpuinfo` and `/proc/meminfo`) to figure out the environment it runs in.

This, however, *is not cgroup aware*. If that is needed, we will have to adapt and either read from the correct place in procfs (seems to be `/sys/fs/cgroup/memory/memory.limit_in_bytes`) and adjust the figures accordingly or do fall back to calling native tools/bundle OSHI)

CPU info is lovely as well. A given environment might have multiple CPUs (server motherboards), multiple physical cores and multiple virtual cores (e.g. due to hyperthreading). While the implementation above exposes all of them, the virtual core count is probably what the user expects, but I am not quite sure yet.
