### ISSUE TITLE
Graph permalinks sometimes(?) zoom into given range but the last day

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#192]
See e.g. http://speedcenter.informatik.kit.edu/velcom/repo-detail/bab50d33-13a1-40c4-85a0-fda5f93f8b22?zoomXStart=1598227200000&zoomXEnd=1602869866418&dimensions=stdlib%3A.olean%20serialization%3AC%20code%20generation%3Acompilation%3Adecl%20post-processing%3Aelaboration%3Aimport%3Ainitialization%3Apage-faults%3Aparsing%3Atask-clock%3Atypeclass%20inference%3Awall-clock: the data until 10/17 is loaded, but only that until 10/16 is shown by default.

**Comment by I-Al-Istannen** [comment]
The actual end date in that URL is `1602869866418`, i.e. `Fri Oct 16 2020 19:37:46 GMT+0200`. That seems to align quite well with the visible range, so the error was introduced earlier.

The share dialog has a checkbox in the top left: `Use X-Axis zoom instead of Start/end date` which is checked by default. If that checkbox is enabled, the currently applied *zoom* will be used instead of the loaded start/end dates. This allows you to also use the share dialog when you are zoomed in and get a more intuitive (I thought) result.

Were you zoomed in when you shared the graph? If not I'll have to investigate that further.
