### ISSUE TITLE
Benchmarking GitHub PRs on request

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#257]
Are you still planning to implement this feature :) ? Since it is the last "killer feature" I'm missing, I thought I might as well create an issue for it.

**Comment by Garmelon** [comment]
Yes, we are. I've already started working on it on the `github` branch, although I'm still trying to figure out how to reliably detect new comments.

**Comment by Kha** [comment]
You've probably thought much harder about this already than I have, but I'm curious why you moved away from the original proposal of using a GitHub Action for that.

**Comment by Garmelon** [comment]
With actions it may be easier to detect new messages, but they are a new environment to program for, setup requires changes to every repo, and (since benchmarks may take quite a long time) would probably need to run for a while. Also, actions can easily become outdated and updates would have to be applied to every repo that uses them.

Implementing this in the VelCom server means that setup is simpler and doesn't affect the tracked repo (just get an api token from github for the bot account and set it for the repo, no need for github secrets etc.) and updates don't require changes in the tracked repo either. Interacting with the GitHub API to send messages is also not really difficult. However, certain interactions (reliably detecting new comments/commands) become a bit more annoying.
