### ISSUE TITLE
Bench repo spec: Why return {"error":"blah"} if it's not presented in a visually pleasing way?

### ISSUE THREAD

**Issue by sgraf812** [IPDSnelting/velcom#302]
I understand that velcom is merely a consumer of the bench repo spec, but why promote returning objects with `error` fields if it's not formatted properly? See http://speedcenter.informatik.kit.edu/compprakt/run-detail/f57ae471-f321-4a56-9c2a-6c2ef9b60162. I wonder: Is the `error` field used in any semantically meaningful way? If not, I suggest removing it and promoting piping to `stderr` instead.

**Comment by I-Al-Istannen** [comment]
Your example is a benchmark script exiting with a code != 0, which is why you get *everything*. Velcom assumes your script crashed and you likely want whatever data you can get.

If the script exits successfully (exit code 0) and returns an `error` key it is interpreted. I don't have a link for that, but a screenshot
![image](https://user-images.githubusercontent.com/20284688/138107704-3fe6f1be-ac7f-491a-942b-be9db6c7e1ec.png)
This was rendered from this bench script:
```sh
#!/bin/bash

echo '{"error": "Hello world"}'
```

----

Additionally, if just a single metric fails (e.g. [here](https://velcom.aaaaaaah.de/run-detail/d471b648-ce65-41e2-9c44-84fb82b73100/8715758a1c0d7e5a72f44fc110af55c5c8f08b5e)), the error message is used. The JSON for the linked run is
```json
{
    "test": {
        "value1": {
            "error": "Could not dingle the dongles"
        },
        "value2": {
            "error": "Failed to fraburgle the kitabonga"
        },
        "Lines C++ with % and many äöüß& special chars <img src=x onerror=alert(1)>": {
            "error": "Unicode is not a solved problem!!"
        }
    }
}
```

**Comment by I-Al-Istannen** [comment]
Do you have any other questions or comments regarding this issue?

**Comment by sgraf812** [comment]
What you say makes great sense, but the bench repo spec https://github.com/IPDSnelting/velcom/blob/main/docs/bench_repo_specification.md#output-format says

> If an error occurs that prevented the benchmark script from running successfully, this format should be used:
> ```
> {
>     "error": <error_string>
> }
> ```
>
> Otherwise, this format should be used:
> ```
> {
>     <benchmark>: {
>         <metric>: <measurements>
>     }
> }
> ```

So I expected I could also return an error "at the top-level". I put up a PR in #311.

**Comment by sgraf812** [comment]
Nevermind, I misunderstood (https://github.com/IPDSnelting/velcom/pull/311#issuecomment-972733996). I'll close this.
