### ISSUE TITLE
Site prefix is not always respected

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#31]
For example, go to http://speedcenter.informatik.kit.edu/velcom/repo-detail, then reload => 404

**Comment by Kha** [comment]
Not sure why the issue wasn't auto-closed (does the commit need to be merged into the default branch via the UI for that?), but anyway, I can still reproduce this on `master` at the above URL (after selecting a repo).

**Comment by I-Al-Istannen** [comment]
Yes, because I am an idiot. Those two pages rewrite their URL dynamically to enable permanent links. Vue-Router wasn't up for that so the pages do it themselves, but ask the router for their own URL. The "full path" vue-router returns does not include the base-url, so that is not respected.

I missed it last time because vue-router *did* correctly rewrite all urls, but some modifications in the page caused it to be overwritten. I will need to see how to catch that properly next time. Would maybe be a nice starting point for UI tests, when the protocol change is finished.
