### ISSUE TITLE
GitHub bot and chip disagree about significance

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#315]
See this comment and linked comparison: https://github.com/leanprover/lean4/pull/815#issuecomment-976261688
Perhaps it got confused about the merge commit?

**Comment by Garmelon** [comment]
This is probably because it got benchmarked before its parent commits. If you rerun the bot, it should show the correct difference.

**Comment by Kha** [comment]
The first parent (from `master`) was successfully benchmarked before the run while the second parent (from the PR) will never be bechmarked, no?

**Comment by Garmelon** [comment]
Hm, that's true. The parent run was benchmarked before the child. In that case, I'll have to look somewhere else.

**Comment by Garmelon** [comment]
If I'm understanding my code correctly, the bot behaved as designed but the design is not ideal:

When the bot is executed on a PR commit, it tries to find the commit in the main branch that the PR branched off of. If it cannot determine this commit unambiguously, it decides it doesn't know what's going on and doesn't select a commit to compare against.

In the example of the lean PR, this is because the bot was executed on a merge commit, from which multiple different main branch commits can be reached. (If the splitting and merging were contained entirely to PR commits, there would have still been an unambiguous branch-off commit the bot would've selected.) Thus it didn't know which branch-off commit to compare against and so it didn't compare against any branch-off commits.

Since no such branch-off commit was found, the "benchmark results" link leads to the run detail view of the commit (as a fallback) instead of the comparison page against the branch-off commit. Coincidentally, one of the parent commits was also a commit on the main branch with useful info. Instead of this fallback, the bot maybe should've sent a message like "Could not unambiguously determine branch-off commit" or something similar.

A possible fix would be to change the bot's message in case it can't determine the branch-off commit. Another possible fix would be to compare against all branch-off commits and then send a message like

> Here are the benchmark results for commit 1ab739b.
> There were significant changes[link] against commit d9b057a:
> \<table\>
> There were significant changes[link] against commit 1234567:
> \<table>

**Comment by Kha** [comment]
If it's not more work, I think selecting the first parent would be perfectly fine

**Comment by Garmelon** [comment]
I've already implemented the more detailed option.

**Comment by Kha** [comment]
Hah, I missed that it includes all information. Sounds good.
