### ISSUE TITLE
Include stddev in significance test

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#41]
By default, changes should probably be marked as significant only if they are larger than twice the standard deviation, though there should be a config variable for e.g. increasing that to 3σ. The default relative difference threshold can probably be lowered from 5% to 1% then (a speedup by 3% *is* a very significant result in compiler construction!).

**Comment by kwerber** [comment]
There are certainly problems with the way significance is currently calculated.
We believe that, to determine significant change, we should also consider including
multiple parent runs of the run in our calculation.

We came up with the following:

To calculate the significance of a run `r` we could do the following for each metric of `r`:

1. Use BFS to get x parent runs of `r`
    - A parent run is a run from a commit that is a (either direct or indirect) parent of the commit which `r` is associated with.
    - Now that we collected all relevant parent runs, we can perform some calculations based on them to
determine the significance of `r`. One such calculation we came up with could be based on differences:

![grafik](https://user-images.githubusercontent.com/1663282/88396877-6ed52280-cdc3-11ea-8019-4b8cc955b4fb.png)

2. For each of these parent runs `p`, calculate the difference between
the value of `p` and the value of each direct parent of `p` and collect all these calculated differences in a list `l` 
    - "value of `p`" meaning the average of all measurement values generated by the benchmark script regarding the current relevant metric.
    - This way we have calculated all the differences that recently happened before this run, which allows us to determine whether or not the difference between `r` and any of its
direct parents is really significant.
    - To do that, we could, for example, calculate the average and stddev of `l` and check if any of the differences between `r` 
and one of its direct parent runs deviates from the average more than y * stddev. (|diff - avg| > y * stddev)

Some additional notes:
- `x` and `y` would be configurable (either globally in the config or per benchmark/metric combination?)
- Step 2 is only one possible calculation we could perform upon the collected parent runs
  - For example, we could also do something with the actual values of the runs themselves instead of the differences

**Comment by Kha** [comment]
Mmh, it's not clear to me what scenarios this is supposed to handle better than the trivial approach (x=0 I suppose).

**Comment by Kha** [comment]
For example, I would not agree that achieving some speedup in a commit makes speedups of the same metric in subsequent commits any less significant.

**Comment by Garmelon** [comment]
> By default, changes should probably be marked as significant only if they are larger than twice the standard deviation [...]
The standard deviation of which values were you referring to?

**Comment by Kha** [comment]
I don't think it should matter; the standard deviation is usually inherent to the metric and shouldn't vary too much from commit to commit. So we can just use the one from the current commit, for example.
